import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import HeaderComp from "./components/Header/HeaderComp";
import FooterComp from "./components/Footer/FooterComp";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <HeaderComp></HeaderComp>
          <div className="root-container">{children}</div>
        <FooterComp></FooterComp>
      </body>
    </html>
  );
}
